### ISSUE TITLE
Goodreads initial critique 

### ISSUE THREAD

**Issue by ChrisDJordan** [carissamelanson/tiy_assignments#1]
The link color for names is a bit inconsistant. I think I see you why you did it, but think there may be a better option. I really enjoy looking at your page, I think you did a great job bringing more character to the site!

<img width="311" alt="screen shot 2015-07-13 at 12 36 38 pm" src="https://cloud.githubusercontent.com/assets/12628873/8656319/7700b9f8-295c-11e5-8d02-49e933dc4e04.png">
<img width="507" alt="screen shot 2015-07-13 at 12 38 57 pm" src="https://cloud.githubusercontent.com/assets/12628873/8656318/76ffeba4-295c-11e5-89de-fe21d7d8f513.png">

**Comment by carissamelanson** [comment]
Thank you for the feedback Chris, it was helpful!
