### ISSUE TITLE
goodreads feedback

### ISSUE THREAD

**Issue by andreastclair** [carissamelanson/tiy_assignments#3]
Really nice use of white space, keeping things clean and and uncluttered. Your grid is consistent and makes it easy for me to go through the page the way (I think) you want me to. But I really do want to click that page title! (The title that is inside of the blue outline box)

I can tell that the header is centered correctly, but it looks off center just because the middle column doesn’t line up with the logo. Maybe that could be fixed by making the search box shorter? 

I love the color combo of the blue and green. It’s fresh, inviting and clean. Maybe a third color would look nice for links? In some places, user names are the bright blue, but in other places they look purple, but I think the purple is too close to the blue to stand out.

**Comment by carissamelanson** [comment]
Thank you for the feedback Andrea, it was very helpful!
