### ISSUE TITLE
Goodreads Mock Up Feedback

### ISSUE THREAD

**Issue by cczapski** [carissamelanson/tiy_assignments#4]
Your strong use of whitespace helps allow the books take the primary focus on pages where books are the main display, but I do agree that your current use of green detracts a little from that in how you have so many different things that color (i.e. titles, reading challenge, buttons). Perhaps try a lighter version of that color.

Overall, the size of your fonts is really small and hard to read. 

Your choice of color and use of the Goodreads book creates a nice, playful tone to the site.

**Comment by carissamelanson** [comment]
Thank you for the feedback Casie, it was very helpful!
