### ISSUE TITLE
GoodReads Initial Feedback

### ISSUE THREAD

**Issue by amatherne** [carissamelanson/tiy_assignments#5]
The colors you chose to highlight are really interesting. They work well together, but maybe use less of the green. It seems to jump off the page in a slightly distracting way. It could be very effective though if used more sparingly. 

Due to flat design trends, your headers (Charlie's Profile, etc) look like buttons. I dig the style of it though. Try extending the height of that box. Try making  it more drastic? Maybe half the size of the blue container above it.

Michael had a point about the header and logo too. A different alignment of the logo and menu options below it might give the header more symmetry. 

Lastly, theres a dark blue you've used a couple times for links. It works well in the big blue box for "The Wiard Of Oz", but seems out of place when used for "Charlie Brown" on the profile page. Doesn't seem to fit with the other blue nearby.

Overall though the spacing and layout are really nice!

**Comment by carissamelanson** [comment]
thanks for the feedback Austin, def helped out!
