### ISSUE TITLE
Goodreads Initial Feedback

### ISSUE THREAD

**Issue by abbylarner** [carissamelanson/tiy_assignments#6]
Layout:
- Overall, you need more of a hierarchy between elements.  Right now because you use both the blue and green as "call to action" colors, it's difficult to know where to look first
- the progress bar on the homepage updates should be placed closer to the information it relates to (Chris's progress), not the action I should be taking ("Want to Read"), consider moving the progress bar above the call to action button
- Always show all 5 books for the ratings so the user knows the maximum possible rating, otherwise it looks like it is always the maximum rating
- Overall, mobile actions need to be much bigger -- your layout of text in the "updates" section will probably need to change on mobile so you can accommodate larger buttons/icons

Design:
- What will the profile picture of a user look like if they actually upload one? right now they are all icons, show both
- Headers on all pages look like clickable buttons (they shouldn't look clickable unless they are)
- everything is left aligned, but your text/icon in your search box look centered, be consistent!
- the nav below the "goodreads" logo doesn't look aligned correctly.  if the alignment is correct within that nav bar, consider differentiating it more from the "goodreads text" -- maybe a darker green background? or just align the navigation links below the logo and keep the margin on either side (between the other two elements) consistent
- Why is the middle arrow grayed out on the mobile version of the profile page?
- Turn the arrows of the closed section to the right to signify that they can be opened
- The search box above the books on the bookshelf page is centered, but everything else is left aligned, be consistent
- What happens to your mobile bookshelf layout if the person has 200 books?

**Comment by carissamelanson** [comment]
Thanks for the feedback Abby! It's all very helpful!
