### ISSUE TITLE
Critique and notes for GoodReads Comps July 13, 2015 FSanger

### ISSUE THREAD

**Issue by fsanger** [carissamelanson/tiy_assignments#7]
Home:
Colors are vibrant and fun.
May be a bit too overwhelming with their use throughout.
large: 
Font size for the menu on lower left seems small.
There may be a bit too much white space on the page overall.
Spacing above and below individual books seems too large.
Box around "Check out..." seems a bit like a control.
small:
Same issue for the space around the individual books.
Could be tightened up a bit for efficiency.

Profile:
This page feels like it's more about books than a profile of a person.
Might be better to have the profile info more at top...
Treatment seems consistent, but a little bare over all.
Same comments for the small version, it seems a little to "light," a bit too cold in feel.

My Books:
Same comments overall.
For large version, books seem well sized, and like the slight drop shadow treatment.
which helps differentiate the white background of books from the white background of the site.
font size for the menu at left seems small.

**Comment by carissamelanson** [comment]
thanks francois! your feedback is very helpful!

**Comment by fsanger** [comment]
Glad if it was, sorry it may have been a bit terse in an effort to get it out.  :(

On Jul 13, 2015, at 7:45 PM, Carissa Melanson notifications@github.com wrote:

thanks francois! your feedback is very helpful!
